server:
  port: 9527

spring:
  application:
    name: cloud-gateway
    ###################网关 不暴露8001 用9527挡。配置文件配置路由
  cloud:
    gateway:
      #开启从注册中心动态创建路由的功能，利用微服务名进行动态路由
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          #lb 是load balance的意思 #uri的协议是lb 表示启用Gateway的负载均衡功能
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址 # 通过微服务名实现动态路由(我这里要大写)
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            - After=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
            # - Before=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
            # - Between=2020-03-08T10:59:34.102+08:00[Asia/Shanghai] ,  2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
            # curl http://localhost:9527/payment/lb --cookie "username=zzyy"
            # - Cookie=username,zzyy   #Cookie=cookieName,正则表达式
            # 请求头要有X-Request-Id属性并且值为整数的正则表达式 curl http://localhost:9527/payment/lb --cookie "username=zzyy" -H "X-Request-Id:11"
#            - Header=X-Request-Id, \d+
#            - Host=**.atguigu.com  # curl http://localhost:9527/payment/lb -H "Host:afae.atguigu.com"
            # - Method=Get
            # - Query=username, \d+ #要有参数名username 且值是整数
#          filters: # 非全局
#            -AddRequestParameter=X-Request-Id, 1024 #过滤工厂会在匹配的请求头上加上一对请求头，名称为X-Request-Id 值为1024

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka